# Generated by Django 4.2.23 on 2025-07-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='전화번호', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(blank=True, help_text='입사일', null=True),
        ),
    ]
