# Generated by Django 5.2 on 2025-07-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='메시지 활성 여부'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(default=True, help_text='세션 활성 여부'),
        ),
        migrations.AddField(
            model_name='docs',
            name='original_file_name',
            field=models.CharField(blank=True, help_text='업로드 시 원래 파일명', max_length=255, null=True),
        ),
    ]
