# Generated by Django 5.2.4 on 2025-07-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='메시지 생성일', null=True),
        ),
    ]
