# Generated by Django 5.2.4 on 2025-07-17 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassign',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='start_date',
        ),
        migrations.AddField(
            model_name='taskassign',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='상위 과제(TaskAssign)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.taskassign'),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='real_end_date',
            field=models.DateField(blank=True, help_text='실제 종료일', null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='real_start_date',
            field=models.DateField(blank=True, help_text='실제 시작일', null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='scheduled_end_date',
            field=models.DateField(blank=True, help_text='예정 종료일', null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='scheduled_start_date',
            field=models.DateField(blank=True, help_text='예정 시작일', null=True),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='status',
            field=models.CharField(blank=True, choices=[('진행전', '진행전'), ('진행중', '진행중'), ('검토요청', '검토요청'), ('완료', '완료')], help_text='과제 상태(진행전/진행중/검토요청/완료)', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
