# Generated by Django 4.2.23 on 2025-07-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_phone_alter_user_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_part',
            field=models.CharField(blank=True, help_text='직무', max_length=50, null=True),
        ),
    ]
