# Generated by Django 5.2.4 on 2025-07-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_taskassign_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassign',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='real_end_date',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='real_start_date',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='scheduled_end_date',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='scheduled_start_date',
        ),
        migrations.AddField(
            model_name='taskassign',
            name='end_date',
            field=models.DateField(blank=True, help_text='종료일', null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='start_date',
            field=models.DateField(blank=True, help_text='시작일', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='메시지 생성일', null=True),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='status',
            field=models.CharField(blank=True, choices=[('진행 전', '진행 전'), ('진행 중', '진행 중'), ('검토 요청', '검토 요청'), ('완료', '완료')], help_text='과제 상태(진행 전/진행 중/검토요청/완료)', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('subtask_id', models.AutoField(help_text='서브태스크 고유 ID', primary_key=True, serialize=False)),
                ('task_assign', models.ForeignKey(help_text='상위 과제 할당', on_delete=django.db.models.deletion.CASCADE, to='core.taskassign')),
            ],
        ),
    ]
