# Generated by Django 5.2.4 on 2025-07-22 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage_is_active_chatsession_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='이메일 주소', max_length=254, unique=True)),
                ('password', models.CharField(help_text='이메일 비밀번호(해시)', max_length=255)),
                ('name', models.CharField(help_text='이메일 발신자 이름', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='start_date',
        ),
        migrations.AddField(
            model_name='mentorship',
            name='report',
            field=models.TextField(blank=True, help_text='멘티 최종 평가', null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='상위 과제(TaskAssign)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.taskassign'),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='real_end_date',
            field=models.DateField(blank=True, help_text='실제 종료일', null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='real_start_date',
            field=models.DateField(blank=True, help_text='실제 시작일', null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='scheduled_end_date',
            field=models.DateField(blank=True, help_text='예정 종료일', null=True),
        ),
        migrations.AddField(
            model_name='taskassign',
            name='scheduled_start_date',
            field=models.DateField(blank=True, help_text='예정 시작일', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='프로필 이미지', null=True, upload_to='profile_img/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='메시지 생성일시', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_text',
            field=models.TextField(blank=True, help_text='메시지 내용', null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_description',
            field=models.TextField(blank=True, help_text='커리큘럼 설명', null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='comment',
            field=models.TextField(blank=True, help_text='메모 내용', null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성일시', null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='user',
            field=models.ForeignKey(blank=True, help_text='유저', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='description',
            field=models.TextField(blank=True, help_text='설명', null=True),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='guideline',
            field=models.TextField(blank=True, help_text='과제 가이드라인', null=True),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='status',
            field=models.CharField(blank=True, choices=[('진행전', '진행전'), ('진행중', '진행중'), ('검토요청', '검토요청'), ('완료', '완료')], help_text='과제 상태(진행전/진행중/검토요청/완료)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taskmanage',
            name='curriculum_id',
            field=models.ForeignKey(db_column='curriculum_id', help_text='소속 커리큘럼', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.curriculum'),
        ),
        migrations.AlterField(
            model_name='taskmanage',
            name='description',
            field=models.TextField(blank=True, help_text='과제 설명', null=True),
        ),
        migrations.AlterField(
            model_name='taskmanage',
            name='guideline',
            field=models.TextField(blank=True, help_text='과제 가이드라인', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.IntegerField(blank=True, help_text='사번', null=True),
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='알림 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('user', models.ForeignKey(help_text='알림 대상 유저', on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
