# Generated by Django 5.2.4 on 2025-07-18 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_taskassign_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 18, 0, 21, 5, 291705, tzinfo=datetime.timezone.utc), help_text='메시지 생성일'),
            preserve_default=False,
        ),
    ]
