# Generated by Django 5.2.4 on 2025-07-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_taskassign_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='메시지 활성 여부'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(default=True, help_text='세션 활성 여부'),
        ),
    ]
